export const OPEN_MAIN_MODAL = 'OPEN_MAIN_MODAL';
export const CLOSE_MAIN_MODAL = 'CLOSE_MAIN_MODAL';
export const CLOSE_HEADER_MODAL = 'CLOSE_HEADER_MODAL';
export const OPEN_HEADER_MODAL = 'OPEN_HEADER_MODAL';
export const ADD_RANDOM_COCKTAIL = 'ADD_RANDOM_COCKTAIL';
